### PR TITLE
Transformer

### PR DESCRIPTION
**Pull request by olfline**
addition to three phase networks
- round transformer shapes (two types) with optional vector groups (zigzag, Y, D)

created a new shape because i did not want to change the existing oosourceshape
- added it to the manual with an example
- mentioned in the CHANGELOG.md

### CODE REVIEW

**Comment by Rmano** [comment]
The failure in the check is not due to your patch, but I will wait till I can fix it, if you don't mind.

**Comment by olfline** [comment]
Ok. I thought, I messed things up. 
There is no need to hurry

**Comment by olfline** [comment]
I'm planing to spend some more time on transformer shapes. Maybe I will edit the PR.
I think that the shapes can be implemented nicer - What do you think?

**Comment by Rmano** [comment]
> I'm planing to spend some more time on transformer shapes. Maybe I will edit the PR.
> I think that the shapes can be implemented nicer - What do you think?

HI, 
I had not time to check them; I am working at a University and I am quite swamped by the preparation phase for the final exams... 

You could add snapshots of the examples to the comments here, it would be nice to preview the shapes in the PR... I try to do it when I remember ;-) 

I will try to look at your code and shapes as soon as I can ;-)

**Comment by olfline** [comment]
> HI,
> I had not time to check them; I am working at a University and I am quite swamped by the preparation phase for the final exams...
> 
> You could add snapshots of the examples to the comments here, it would be nice to preview the shapes in the PR... I try to do it when I remember ;-)
> 
>I will try to look at your code and shapes as soon as I can ;-)

Thanks for replying so fast!
If you dont have much time at the moment, it's totally OK.

I included the screenshots of the manual; the shapes shall look like the following.
Maybe, I can improve them...

github2
github1

**Comment by Rmano** [comment]
I am not used to this kind of symbols (not my field) but I find this one: 

image

somewhat asymmetric --- it seems that the vertical circles are overlapping more than the others. But it could be a rounding error, I don't know.

**Comment by olfline** [comment]
I made some changes, including the spacing issue.

**Comment by Rmano** [comment]
Adding a snapshot...:

image

They seem all ok to me. If you think they are finished, for me they are GTM (good to merge).

**Comment by olfline** [comment]
I think, they are good to go. Tanks for merging :)

**Pull request merged**
