### PR TITLE
Fix a typo (voilá -> voilà)

### PR DESCRIPTION
**Pull request by quark67**
It's the word "voilà" in English (see https://en.wiktionary.org/wiki/voilà#English), from the French "voilà". The word "voilá" seems to be Spanish (https://en.wiktionary.org/wiki/voilá).

### CODE REVIEW

**Comment by quark67** [comment]
More changes in the file are provided. Notice that on line 677, I changed "artefacts" to the word "artifacts" that is the American English spelling. On line 1480, I changed "affect also" to "also affect" because a grammar checker says that "***Also** must be placed before the main verb*" (same on lines 2335 & 3499 & 3597 & 3829). On line 1722, I rephrased the text, because according to the grammar checker, "*The verb **want** cannot be followed by a clause introduced by **that***" (same on line 1981). On line 1745, I remove the plurial of "circuits" because the grammar checker says "***Circuit** should be singular because it modifies the noun **blocks***", but I'm not sure if this is true (same on the line 1754 for the word "anchors" and on line 1950 for the word "grounds"). On line 2069: "*Because **circuits** follows **kind of**, it should be singular*.". Line 2124: I conjugate the verb with the plural of "elements", but perhaps you prefer a singular "element"? On lines 2594 & 2596 and 2626 & 2628, I'm use the American English spelling "behavior". On line 3521, there is a "O" alone on the line. I suppress it, but perhaps there is a missing phrase here (or it's the "o" I added on line 3520 for correcting "bth" to "both")? On line 3532: "*Adverbs of frequency should come directly before the verb.*". 
I'm at line 4000 yet. Will continue later.

**Comment by Rmano** [comment]
Thank you! Tell me when you got tired by this (no doubt you will 😉) and I'll merge.

**Comment by quark67** [comment]
On line 4352, I made some changes that need to be verified. I'm not sure if I'm right (I also change "to align" by "aligning" because "*The verb **permit** must be followed by a gerund (-ing form) in this context.*" (same on line 5908 with "having"). On line 4640, I replaced "that" by "which", fell free to reverse this. Line 4807, I add the word "with". On line 5278: "***Also** must be placed before the main verb.*" (same on lines 5293 & 5331 & 6188 & 6524 & 6849 & 7665). On 5336, perhaps you can change "10-point" by "10 pt"? I don't have made the change because it's more a suggestion than a correction. On line 5371, I replace "are" by "is" because the subject is singular (the length). On line 5831, I replace "They" by "the" but perhaps "These" is more appropriate? On line 6042, the grammar checker says: "*When **have** is not used as an auxiliary, you should use the auxiliary **do** to make the negative form*." On line 6068, the grammar checker says: "The verb **go** should be in the base form when it follows a modal auxiliary such as **can**." On line 6126, the grammer checker says: "*The **noun** connection requires the verb make, not **do***." On line 6284, the verb "do" is in plural because the subject "proportions" is plural. On line 6774, I replace "do" by "make". On lines 7554 & 398 & 2724 & 4904, I replace "labelling" by "labeling" (American English spelling). On line 7563, I replace "behaviour" by "behavior" (American English spelling). On line 7698, I replace "drawn" by "draw" because "*The particle **to** should be followed by the base form of the verb **draw***".
I'm at line 800 yet. Will continue tomorrow.

**Comment by Rmano** [comment]
Thanks a lot!
You do not need to spell out the changes in the comments unless you want to point out something special --- I am reviewing the patches and will comment if I find something I do not understand. (Hoping that this is some less work from you).

**Comment by quark67** [comment]
On line 9184, I replaced "are" by "is" because "component" is singular. But perhaps you prefer that "component" is plural? On line 9251, "*Adverbs of frequency should come directly before the verb*." On line 9325, "*The verb **move** should be in the base form when it follows the auxiliary verb **does***". On lines 1475 & 9507, I replace "ok" by "OK" which is more correct. On line 200 & 1303 & 1473 & 1705 & 1961 & 8774, I replace "Ti\emph{k}Z" by "\TikZ\ " (forgotten yesterday). 
Since I am not a native English speaker, I probably missed some typos. And I also left out a number of commas that would probably be better inserted but the priority was to correct the typos.

**Comment by Rmano** [comment]
Hi, I'd like to release a minor version soon... so please add a line to CHANGELOG.md with credits (yours!) for the typo/grammar-o squashing ;-), then I'll merge this!

**Comment by quark67** [comment]
Done.

**Pull request merged**
