### PR TITLE
Adding optional bulk connection to nmos and pmos

### PR DESCRIPTION
**Pull request by Rmano**
Thanks to Burak Kelleci <kellecib@hotmail.com> who sent this patch by email. 

Sorry for the space(s) noise...

### CODE REVIEW

**Comment by Rmano** [comment]
image

**Comment by Rmano** [comment]
image

**Comment by alexpacini** [comment]
When the bulk terminal is used, it is frequent to see the arrow in the bulk terminal.

**Comment by Rmano** [comment]
> When the bulk terminal is used, it is frequent to see the arrow in the bulk terminal.

Yes, but in that case probably `nfet` and `pfet` are better matches? If you want the solid gate, though, you can add arrows using the anchors... I fear a bit adding even more options.

**Comment by Rmano** [comment]
@alexpacini  Sedra-Smith convinced me: https://electronics.stackexchange.com/questions/77859/why-does-circuitlab-have-the-mosfet-symbols-it-has --- I think that I will let the bulk unmarked; maybe I could add a "solid gate" option to `nfet` and `pfet` if the need arises.

**Pull request merged**
