### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**

### CODE REVIEW

**Comment by Rmano** [comment]
No idea why the Travis check failed the first time. Restarted

**Comment by yashpalgoyal1304** [comment]
yeah sure, 

the only reason i kept this as draft was for more typos on my next read (which is still pending 😅). i will open a new pr for those if i find any.

**Comment by yashpalgoyal1304** [comment]
just curious, is the access to mark it "ready for review" only with the author (here, that's me) or is it with maintainers (that's u) too? i think it should be latter, but want to confirm.

**Comment by Rmano** [comment]
> just curious, is the access to mark it "ready for review" only with the author (here, that's me) or is it with maintainers (that's u) too? i think it should be latter, but want to confirm.

I *think* it's the former... Next time I'll check!

Thanks

**Comment by yashpalgoyal1304** [comment]
i really should start naming my branches properly 🤦 - will try to keep it in mind in future

I came to know about this point about branches having proper names from newpipe pull request template:
* https://github.com/TeamNewPipe/NewPipe/pull/3132/files#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R22

**Pull request merged**
