### PR TITLE
added optical fiber

### PR DESCRIPTION
**Pull request by dl1chb**
Added a block diagram symbol for an optical fiber

### CODE REVIEW

**Comment by Rmano** [comment]
Hi, thanks for you contribution. 

The problem is that you are not using the new (since last year, more or less) macros for creating blocks; so you really are undoing the block rotation. You can check it with the following code:

```latex
\documentclass[]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[siunitx, RPvoltages]{circuitikz}
\usepackage{ctikzmanutils}


\begin{document}

\begin{groupdesc}
     \circuitdescbip*{fiber}{Optical Fiber}{}
\end{groupdesc}

Example:

\begin{LTXexample}[varwidth=true]
\begin{tikzpicture}[scale=0.9]
    \ctikzset{blocks dc segments=3}
    \draw (0,2) to[sacdc] ++(2,0)
        to[fiber, t=G] ++(2,0);
\end{tikzpicture}
\end{LTXexample}

Check blocks orientation:

\begin{LTXexample}[varwidth=true, pos=t]
\foreach \bl in {sacdc, fiber} {
    \begin{tikzpicture}[]
        \draw (0,0) to[\bl, t=P, >] ++(3,0)
            to[\bl, t=P, >] ++(0,-3)
            to[\bl, t=P, >] ++(-3,0)
            to[\bl, t=P, >] ++(0,3);
    \end{tikzpicture}\qquad
}
\end{LTXexample}
\end{document}
```

image

I can fix it and merge, or you can fix it --- whatever you prefer. You can look at this commit for example:

https://github.com/circuitikz/circuitikz/pull/762/commits/b7bac4186ae19386ba87d8184fcd4ad2367794bd

**Comment by dl1chb** [comment]
Hi, thanks for checking that. If it does not take too much of your time would appreciate if you could fix and merge it. I will then take more care of it for other symbols.

**Comment by Rmano** [comment]
Ok, no problem. So your code is completely equivalent (well, better than this: now you have generic anchors etc.) to

```
\ctikzset{bipoles/fiber/width/.initial=.7}
%% optical fiber
\pgfcirc@define@twoports{blocks}
{}
{\ctikzvalof{bipoles/fiber/width}}
{fiber}
{\ctikzvalof{bipoles/fiber/width}}
{\ctikzvalof{bipoles/fiber/width}}
{
	\pgfpathcircle{\pgfpoint{0.2\pgf@circ@res@left}{6}}{6}
	\pgfpathcircle{\pgfpoint{0\pgf@circ@res@left}{6}}{6}
	\pgfpathcircle{\pgfpoint{-0.2\pgf@circ@res@left}{6}}{6}
	\pgfusepath{draw}
        % always use basic line width for this
        \pgfsetlinewidth{\pgfstartlinewidth}
        \pgfpathmoveto{\pgfpoint{\pgf@circ@res@left}{\pgf@circ@res@zero}}
        \pgfpathlineto{\pgfpoint{\pgf@circ@res@right}{\pgf@circ@res@zero}}
	\pgfusepath{draw}
}

\pgfcirc@activate@bipole@simple{l}{fiber}
```

because all the "standard" (dashed, arrow, etc.) code is taken into account by the macro. Also, for now the standard is to define a new key for the size of every block (I'll change it in v2.0.0... but not now).

But I am not user if you prefer to change  `\pgfcirc@define@twoports{blocks}` with `\pgfcirc@define@twoports@norotate{blocks}`; in the latter case, the output will be: 

image

Notice how now the fiber loop follow the lines now.

**Comment by Rmano** [comment]
Another problem: look: 

image

...you are using fixed size (6pt) for the circle; everything must be scald with the size of the block, otherwise the scale of the class will not work correctly.

I'll fix this also, ok? Tomorrow or something like that, now I have no time.

**Pull request merged**
