### PR TITLE
Re-fix label position

### PR DESCRIPTION
**Pull request by Rmano**
Back to base anchor, to avoid to have to workaround alignement of
label with depth. Avoid scaling of ex distances in labels, though.

### CODE REVIEW

**Comment by Rmano** [comment]
Closing and opening to retrigger a build

**Comment by sistlind** [comment]
I often searched for an option to get this scalings correctly. Great achievement that you got this to work!
It is really a pity that the tikz documentation is such a mess that often only tex stackexchange could help.

Nevertheless, I found a minor issue at page 72 in the manual:
image

It seems that the anchor position is not computed properly at angled paths.

**Comment by Rmano** [comment]
Good catch. I'll see if I can dig this out...

**Comment by sistlind** [comment]
Hi Romano,
that looks good now, but I found another tiny problem at one of my old tests for this problem:
Code:
```
\documentclass[]{article}
\usepackage[]{circuitikz}

%\ctikzset{label/align = rotate}
\begin{document}%
\pgfcircversion{}
	\begin{tikzpicture}%
	\def\DIR{0,45,...,350}
	\foreach \i	in \DIR {
	\draw (\i:2)node{x} to[R,l=LLyy, a=aaaa] (\i:4)to[R,l=LLyy, a=Aaa] (\i:6) ++(\i:1)node{\i};
	}
	\end{tikzpicture}
\end{document}
```
At this example all anchors are aligned at the base except at the case for 0&180 degree.
grafik

**Comment by Rmano** [comment]
I have changed the implementation again; this time the rotated label should be ok (tested with various zooms). I will look that anchor next...

**Comment by Rmano** [comment]
@sistlind , do you know how to restart a travis CI build without closing/reopening the PR?

**Comment by Rmano** [comment]
This is really strange... this is what I have with your code: 

image

**Comment by Rmano** [comment]
@sistlind  I am trying a more clean approach. All the distances are calculated the same way, and I have added a strut to the text to avoid the problem with ascendant in north-anchored labels. 

```
\documentclass[]{article}
\usepackage[]{circuitikz}

% \ctikzset{label/align = rotate}
\begin{document}%
\pgfcircversion{}
\begin{tikzpicture}[scale=0.8]%
	\def\DIR{0,45,...,350}
	\foreach \i	in \DIR {
	\draw (\i:2)node{x} to[R,l=LLyy, a=aaya] (\i:4)to[R,l=mmyy, a=Aaya] (\i:6) ++(\i:1)node{\i};
	}
	\end{tikzpicture}
\end{document}
```

results in 

image

**Pull request merged**
