### PR TITLE
Change arrows for transistors with a fill-only one

### LINKED ISSUE #302: Mos arrows slightly overrunning ends
Burak Kelleci <kellecib@hotmail.com> discovered that when drawing MOS arrows and using `arrows pos=end`, the tip of the arrows overshoot a little. Consider 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}
\ctikzset{tripoles/mos style/arrows}
\ctikzset{tripoles/pmos style/emptycircle}
\ctikzset{transistors/arrow pos=end}

\draw (0,0) node[nmos] (mos1) {} (mos1.gate) node[left] {G}
(mos1.drain) node[above] {D} -- (mos1.source) node[below] {S};

\draw (2,0) node[pmos] (mos2) {} (mos2.gate) node[left] {G}
(mos2.drain) node[below] {D} -- (mos2.source) node[above] {S} ;
\end{circuitikz}
\end{document}
```

gives: 
image

with more zoom: 
image

### PR DESCRIPTION
**Pull request by Rmano**
The arrow should be (more or less) the same size then the
filled+stroked currarrow used before.
We have two tip arrow, one exact and one that let the arrow overshoot a
bit for aesthetic reasons.

Fixes #302

### CODE REVIEW

**Comment by Rmano** [comment]
This is a new idea to fix #302

This is not an "exact" solution, but it's an approximation. Notice that the "spy" things are not exact, but they give an idea. 

image

[test-tr-arrows.pdf](https://github.com/circuitikz/circuitikz/files/3780686/test-tr-arrows.pdf)

**Comment by Rmano** [comment]
These are with default linewidth doubled (better for online, given the crappy antialiased viewer we have around): 

image

image

**Comment by Rmano** [comment]
@BurakKelleci what do you think? I feel it is sufficient...

**Comment by Rmano** [comment]
Ok, with this code: 
[test-tr-arrows.zip](https://github.com/circuitikz/circuitikz/files/3784928/test-tr-arrows.zip)

I have this result WITH this PR: 
[test-tr-arrows-PR.pdf](https://github.com/circuitikz/circuitikz/files/3784930/test-tr-arrows-PR.pdf)

And this is the original: 
[test-tr-arrows-master.pdf](https://github.com/circuitikz/circuitikz/files/3784933/test-tr-arrows-master.pdf)

If you change the linewidth, please notice that the `spy` windows are not precise anymore --- they do not take into account the different scale for lines when using `\pgflinewidth`(*). 

(*) which is probably a problem in `circuitikz`, not in `spy`, but well....

**Comment by Rmano** [comment]
With this file: 
[lots_of_circuits.zip](https://github.com/circuitikz/circuitikz/files/3784959/lots_of_circuits.zip)

I have without:
[lots_of_circuits-master.pdf](https://github.com/circuitikz/circuitikz/files/3784962/lots_of_circuits-master.pdf)

And with:
[lots_of_circuits-PR.pdf](https://github.com/circuitikz/circuitikz/files/3784968/lots_of_circuits-PR.pdf)

**Comment by BurakKelleci** [comment]
I think it is sufficient and pretty good.

**Pull request merged**
