### PR TITLE
Add ferroelectric capacitors

### PR DESCRIPTION
**Pull request by Rmano**
Suggested by  Mayeul Cantan
see https://github.com/circuitikz/circuitikz/issues/515

image

image

### CODE REVIEW

**Comment by Rmano** [comment]
Ok, now I have added this:

image

Adding extra anchors here will be at least a bit complex (and they will be global, in the sense that if you change the shape parameters mid-circuits they will be wrong), but I can try. Do you think it's worth the effort adding the anchors?

**Comment by Rmano** [comment]
image

**Comment by Rmano** [comment]
image

**Comment by MayeulC** [comment]
> Adding extra anchors here will be at least a bit complex (and they will be global, in the sense that if you change the shape parameters mid-circuits they will be wrong), but I can try. Do you think it's worth the effort adding the anchors?
> 
> Again, I am open to change the option name if it sounds... itanglish. @MayeuIC

It looks good, I am not really concerned wirh the name either, as long as it is easy to remember. Thanks again for including the fill option!

As for the feedback I gathered, for now I haven't seen anything but praise about these figures. Maybe just some mentions that the symbol was a bit hard to read with the bulk (pfet symbol), but that was expected.

**Comment by MayeulC** [comment]
I am wondering if the best way to have the line terminator (PL) not filled is to draw it in another node?
image

```latex
	\begin{circuitikz}
		[scale=1.2]\draw
		(1,0) node[nfet,rotate=-90] (t) {} % t nfet, empty label
		(t.S) to[short, -o] (0,0) node[left] {$BL$}
		(t.G) to[short, -o] +(0,0.3) node[left] {$WL$}
		(t.D) -| (2,0) node[right] {$n$} to[feC, *-o, fill=cyan] (2,-1) node[left] {$PL$}
		(t.bulk) -- +(0,0) node[ground,scale=0.7] {};
	\end{circuitikz}
```
Like so:
```latex
	\begin{circuitikz}
		[scale=1.2]\draw
		(1,0) node[nfet,rotate=-90] (t) {} % t nfet, empty label
		(t.S) to[short, -o] (0,0) node[left] {$BL$}
		(t.G) to[short, -o] +(0,0.3) node[left] {$WL$}
		(t.D) -| (2,0) node[right] {$n$} to[feC, fill=cyan] (2,-1)  to[short, *-o] (2,-1) node[left] {$PL$}
		(t.bulk) -- +(0,0) node[ground,scale=0.7] {};
	\end{circuitikz}
```

It's the simplest I can come up with, but I am wondering if there is something more specific like `dielectric fill=cyan`?

**Comment by Rmano** [comment]
Yes. If you say `to[feC, *-o, fill=cyan]` the fill apply to the `*-o` to. You should do `to[feC, *-, fill=cyan] (2,-1) node[ocirc]{}` also (to avoid the zero-sized `to` --- it works but really can give surprises).  

Probably the best way is to use a locally defined style on capacitors only:

     to[feC, *-o, capacitors/fill=cyan] (2,-1) 

And if you use that a lot you can define a style:

```latex
\tikzset{cyan feC/.style = {feC, capacitors/fill=cyan}}
\begin{tikzpicture}
    [scale=1.2]\draw
    (1,0) node[nfet,rotate=-90] (t) {} % t nfet, empty label
    (t.S) to[short, -o] (0,0) node[left] {$BL$}
    (t.G) to[short, -o] +(0,0.3) node[left] {$WL$}
    (t.D) -| (2,0) node[right] {$n$} to[cyan feC, *-o](2,-1)  node[left] {$PL$}
    (t.bulk) -- +(0,0) node[ground,scale=0.7] {};
\end{tikzpicture}
```

**Comment by Rmano** [comment]
Anyway --- if you want to submit one of your circuits to the "examples" section, feel free! ;-)

**Comment by MayeulC** [comment]
I am wondering if the best way to have the line terminator (PL) not filled is to draw it in another node?
image

```latex
	\begin{circuitikz}
		[scale=1.2]\draw
		(1,0) node[nfet,rotate=-90] (t) {} % t nfet, empty label
		(t.S) to[short, -o] (0,0) node[left] {$BL$}
		(t.G) to[short, -o] +(0,0.3) node[left] {$WL$}
		(t.D) -| (2,0) node[right] {$n$} to[feC, *-o, fill=cyan] (2,-1) node[left] {$PL$}
		(t.bulk) -- +(0,0) node[ground,scale=0.7] {};
	\end{circuitikz}
```
Like so:
```latex
	\begin{circuitikz}
		[scale=1.2]\draw
		(1,0) node[nfet,rotate=-90] (t) {} % t nfet, empty label
		(t.S) to[short, -o] (0,0) node[left] {$BL$}
		(t.G) to[short, -o] +(0,0.3) node[left] {$WL$}
		(t.D) -| (2,0) node[right] {$n$} to[feC, *-, fill=cyan] (2,-1)  to[short, -o] (2,-1) node[left] {$PL$}
		(t.bulk) -- +(0,0) node[ground,scale=0.7] {};
	\end{circuitikz}
```

It's the simplest I can come up with, but I am wondering if there is something more specific like `dielectric fill=cyan`?

---
I also have been encountering this pet peeve of mine for a few years: though it isn't a big matter, the lines on the transistor aren't aligned with the connectors. I assume this is known? Is this fixable? That looks like floating point issues.

**Comment by MayeulC** [comment]
Thanks a lot for the suggestions! I'll definitely think about submitting an example circuit, though these are quite simple compared to the current examples. Should I submit one of the more complex ones?

---
Also visible on the screenshot is this pet peeve of mine: though it isn't a big matter, the lines on the transistor aren't aligned with the connectors. I assume this is known? Is this fixable? That looks like floating point rounding issues, as it isn't visible at every zoom level.

**Comment by Rmano** [comment]
Whatever --- there are a lot of things in examples, so a small to the average circuit is the best one. 

The alignment problem: this is typically an antialiasing glitch of the PDF viewer. Try to print it and check... Your circuit at 1600% comes out like this in `okular`:

image

But at 200%:

image

(`okular` is pretty bad at this). I really do not know *why* it happens, but there must be some rounding around that make the viewer thinks it has to do antialiasing in a different way for the different parts...

**Pull request merged**
