### PR TITLE
Fix a bug for context

### PR DESCRIPTION
**Pull request by Rmano**
Thanks to A. Licari-Guillame for noticing and
to Max Chernoff for suggesting the changes.

https://tex.stackexchange.com/questions/705661/circuitikz-and-perpendicular-coordinates-in-context https://tex.stackexchange.com/questions/705681/circuitikz-and-transformer-core-in-context

### CODE REVIEW

**Comment by Rmano** [comment]
Notice that the fix for context is not working in recent installations, because the main circuitikz file is overridden in the context distribution. I'll try to fix it there too...

**Comment by Rmano** [comment]
@adityam (not knowing if the ping would work), can you have a look at this? I think it needs the change applied to `m-circuitikz` file in the distribution, similar to what happened to https://github.com/circuitikz/circuitikz/issues/706

**Comment by adityam** [comment]
The ping works!This is a cat code issue and the proposed fix is the simplest way to fix it. I can propose the fix to Hans in a day or two (or Max could do it ). On Dec 25, 2023, at 6:00 PM, Romano Giannetti ***@***.***> wrote:﻿
@adityam (not knowing if the ping would work), can you have a look at this? I think it needs the change applied to m-circuitikz file in the distribution, similar to what happened to #706

**Comment by Rmano** [comment]
> The ping works!This is a cat code issue and the proposed fix is the simplest way to fix it. I can propose the fix to Hans in a day or two (or Max could do it ). 

@adityam thanks, that will do.

**Comment by adityam** [comment]
Please note that the catcode fix is also included in context `2024.01.08`. So the first bug reported on tex.se works correctly with the latest beta

**Pull request merged**
