### PR TITLE
[WIP] Fixing typos in the manual

### PR DESCRIPTION
**Pull request by asinghvi17**
Hi,
First of all - thanks for this package!  I've been using it for a couple of weeks now, and I really like the functionality.

I noticed some typos in the manual that I wanted to fix.  I'm not quite done with going through it all yet, and I would like to give it a couple of passes, but this should hopefully fix some of the typos and such.  Minor stuff, but it does help polish it up a bit :)

### CODE REVIEW

**Comment by Rmano** [comment]
...and by the way, thank you for the review, it's really welcome.

**Comment by asinghvi17** [comment]
Oh yeah, that was just to fix an issue Atom was having pulling the files.  I will roll it back shortly :)...sorry that didnt have much explanation

**Comment by Rmano** [comment]
Hi @asinghvi17  --- how are you? I'd like to prepare a release this week, and I would like to merge your fixes...

**Comment by asinghvi17** [comment]
@Rmano, sorry for letting this go stale.  I think that at this point there isn't much more I'll be able to do in a reasonable timeframe - as I use the manual and find stuff I want to change I'll open more PRs.  Let me fix the gitignore in a couple of hours when I get back to my computer, and then feel free to merge!

**Comment by asinghvi17** [comment]
@Rmano should be good to merge now!

**Pull request merged**
