### PR TITLE
add resistive splitter

### PR DESCRIPTION
**Pull request by matthuszagh**
Adds a resistive splitter. I've basically just copied the wilkinson divider code and added two resistors. It looks like this:

splitter

The code could be cleaned up a bit (i.e., put the repeat parts in a loop), but I wanted to get your opinion on adding this node before doing that. I've used a "delta" splitter (see [here](https://www.microwaves101.com/encyclopedias/resistive-power-splitters)) as a generic splitter symbol. We could also use separate delta and wye splitters, which would involve moving some of the internal graphics for the wye splitter, but shouldn't be too tough. Anyway let me know your thoughts.

### CODE REVIEW

**Comment by Rmano** [comment]
I think it is OK, I am not an expert in those symbols but it's clean. I'll let you decide if you want to add the wye version too.
Maybe you should also add attribution (to you) in the manual, look at the gridnode symbol after yours :-)

**Comment by Rmano** [comment]
BTW, I just merge the transmission gate --- it seems that this will merge ok, but please check it!

**Comment by Rmano** [comment]
BTW, I'll wait for your answer about this --- I would like to do a release during the weekend, and I'd like to include your symbol(s)!

**Comment by matthuszagh** [comment]
I think its fine to leave the generic version as the delta splitter. It was my impression that this is meant to represent a splitter in an abstract way (which I believe this does), not really its internal implementation. For that you'd probably want to be drawing out the resistors as discrete components anyway. However, happy to defer to you if you disagree.

In any event, I've refactored the repeat parts into a loop, rebased on top of your latest commits and added the attribution in the documentation so this should be good to go for your next release!

**Comment by matthuszagh** [comment]
Ignore the close, that was unintentional...

**Comment by dl1chb** [comment]
wilkinson divider (and combiner), gysel (divider), resisitive splitter (this one here in this issue), MMI (will be a new component from me, but it can act as an an optical divider), optical beam-splitter (as you know from all those optical desks looking like a prism), but one generall power devider? is there a symbol anywhere? what do you thinkt for this to be a new issue?

**Comment by Rmano** [comment]
@dl1chb  I am not qualified about this kind of symbols --- never worked in this field. @matthuszagh  seems to know a lot more, what do you think?

**Comment by Rmano** [comment]
@dl1chb if you want to add a new component, I'll prefer a new issue/PR --- thanks!

**Comment by matthuszagh** [comment]
I know less than @Rmano is giving me credit for, but @dl1chb feel free to tag me if you open a new issue/PR and I'll take a look.

**Pull request merged**
